# Site settings
title: Git Reference
description: A reference of tasty tips, getting out of a git pickle and overcoming the road-blocks
favicon: "/assets/images/favicon.ico"
baseurl: "/gitreference"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
